[package]
name = "photobuf"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[dependencies]
quicli = "0.3.0"
hyper = "0.12.2"
hyper-tls = "0.2.1"
futures = "0.1.21"
tokio-timer = "0.2.4"
